from Src.Logics.processes.process_factory import process_factory
from Src.Logics.processes.abstract_process import abstract_process
from Src.Logics.processes.process_storage_turn import process_storage_turn